	Python3 anaconda is now loaded in your environment.

	CUDA-10.2 loaded

Global seed set to 38
[2022-05-17 00:18:37,302] INFO: Building data: hotel_location...
[2022-05-17 00:18:37,437] WARNING: Reusing dataset hotel_location_dataset (/jmain02/home/J2AD003/txk58/zxz22-txk58/.cache/huggingface/datasets/hotel_location_dataset/hotel_location_dataset_/0.0.0/7761d47f3e9857ffd48d4532cc06ee7af8384f00f2909e9d5326e3fdd5e6e777)
  0%|          | 0/3 [00:00<?, ?it/s] 33%|███▎      | 1/3 [00:00<00:00,  7.16it/s]100%|██████████| 3/3 [00:00<00:00, 16.76it/s]
Traceback (most recent call last):
  File "/jmain02/home/J2AD003/txk58/zxz22-txk58/.conda/envs/spectra/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/jmain02/home/J2AD003/txk58/zxz22-txk58/.conda/envs/spectra/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/jmain02/home/J2AD003/txk58/zxz22-txk58/spectra/spectra-rationalization/rationalizers/__main__.py", line 109, in <module>
    train.run(args)
  File "/jmain02/home/J2AD003/txk58/zxz22-txk58/spectra/spectra-rationalization/rationalizers/train.py", line 24, in run
    dm.setup()
  File "/jmain02/home/J2AD003/txk58/zxz22-txk58/spectra/spectra-rationalization/rationalizers/data_modules/hotel_location.py", line 112, in setup
    download_mode=hf_datasets.GenerateMode.REUSE_DATASET_IF_EXISTS,
AttributeError: module 'datasets' has no attribute 'GenerateMode'
